### ISSUE TITLE
Templom 0 minden keresésnél megjelenik

### ISSUE THREAD

**Issue by markszabo** [borazslo/miserend.hu#113]
0-s számú templom minden keresésnél megjelenik, pl: [link](http://miserend.hu/index.php?kulcsszo=&varos=Ter%C3%A9ny&hely=&tavolsag=4&ehm=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&espker=0&tnyelv=0&mikor=2018-10-21&mikordatum=2018-10-21&mikor2=0&mikorido=8%3A00-19%3A00&nyelv=0&zene%5B%5D=cs&zene%5B%5D=g&zene%5B%5D=na&kor%5B%5D=ifi&kor%5B%5D=d&kor%5B%5D=csal&kor%5B%5D=na&ritus=0&liturgy%5B%5D=ige&q=SearchResultsMasses)

![selection_003](https://user-images.githubusercontent.com/12611720/47271150-0b76ea80-d576-11e8-9a1e-8526b4f472f7.png)

A templom linkje ide mutat: http://miserend.hu/templom/0

**Comment by borazslo** [comment]
Upsz. Köszönöm. Javítva. 

Valahogy bekerült az adatbázisba egy 0 azonosítójú templomhoz tartozó mise. De ilyen templom nincs. Ezt most töröltem. Így a probléma nem áll fenn.

Hosszabb távú kérdés, hogy
- hogyan jöhetett létre ilyen
- be kell-e építeni mechanizmust, hogy kiszűrje az ilyen anomáliát
