### ISSUE TITLE
bower helyett Yarn / webpack

### ISSUE THREAD

**Issue by connorhu** [borazslo/miserend.hu#121]
https://bower.io/blog/2017/how-to-migrate-away-from-bower/

Célszerű migrálni a csomagkezelést yarn alá és a kódok kezelését webpack alá.

**Comment by borazslo** [comment]
Dockerizálva lett most minden. Csomagkezelés részben `npm` (package.json) és azon belül még can `composer` (composer.json). Bower ki lett iktatva: 6ec70ec5a9b7b04db8561d1cea6d7262e905f280

Így jobb? Van még hovatovább migrálni?
