### ISSUE TITLE
External API

### ISSUE THREAD

**Issue by borazslo** [borazslo/miserend.hu#124]
Azt hiszem akkor csinál ilyet, ha aznapra túl sok kérés futott már le. Kezelni kéne a választ.

```
External API return data is not a valid JSON! (route?from=48.1599524,22.2787256&to=48.1857001,22.3124395&outFormat=json&unit=k&routeType=shortest&narrativeType=none&doReverseGeocode=false&key=***)

ExternalApi\ExternalApi::downloadData()/home/miserend_hu_git/github/borazslo/production.miserend.hu/classes/externalapi/externalapi.php:28 -> downloadData()
ExternalApi\ExternalApi::runQuery()/home/miserend_hu_git/github/borazslo/production.miserend.hu/classes/externalapi/mapquestapi.php:23 -> runQuery()
ExternalApi\MapquestApi::distance()/home/miserend_hu_git/github/borazslo/production.miserend.hu/classes/distance.php:80 -> distance()
Distance::MupdateChurch()/home/miserend_hu_git/github/borazslo/production.miserend.hu/classes/html/church/church.php:40 -> MupdateChurch()
Html\Church\Church::__construct()/home/miserend_hu_git/github/borazslo/production.miserend.hu/classes/html/church/church.php:110 -> __construct()
Html\Church\Church::factory()/home/miserend_hu_git/github/borazslo/production.miserend.hu/index.php:30 -> factory()

```

**Comment by borazslo** [comment]
Azért itt kéne még dologzni:
- megjegyezni, ha 403 és nem próbálkozni egy darabig?
- valahol nyomon követni a lekéréseket?
- biztos kell ennyi lekérés?

**Comment by molnarm** [comment]
Most vettem észre, hogy tegnap összedöntöttem a miserend.hu-t a molnarm/liturgia.tv#17-tel, nem tudta lekezelni az átirányítást. Most megcsináltam, hogy az API ne adjon vissza ilyet, aztán majd írd át az új domainre. (Meg érdemes átgondolni, hogy el kell-e szállnia az egész oldalnak exceptionnel, ha valami külső adat épp nem elérhető...)

**Comment by borazslo** [comment]
Remélem javítva a domain-t.

Egyébként tök jogos, hogy miért hall le minden egy external api leállástól. Oh, szegény kódocska olyan rossz állapotban van. Csoda, hogy működött eddig. Most, hogy hozzányúlok, bárhol, hát van minden. Na majd talán szépen lassan.

Köszi

**Comment by borazslo** [comment]
Jobb már: nem hal le minden. Azért még kell valamit kezdeni, de az már külön dolog: #129
