### ISSUE TITLE
Mobilos adatlap

### ISSUE THREAD

**Issue by foldesistudio** [borazslo/miserend.hu#149]
### Kedves Elek László!

Köszönöm a kiváló tájékoztató oldal fejlesztését. Külön öröm, hogy a github információk is megjelennek a footer-ben. 

**Továbbá észrevettem:**
A church template -ben a show oldalon mobilos nézetben sajnálattal tapasztaltam, hogy "hidden-xs" class bekerült. Szerettem volna mobilról megnézni az adatokat, de emiatt nem sikerült.

Szerintem az alábbiak jelenjenek meg mobilon a már meglévőkön túl:

- Kapcsolódó információk
- Bemutatkozás
- Elhelyezkedés
- Kapcsolat - elérhetőség

Ha van rá mód, akkor szívesen segítek a fejlesztésben.

Minden jót,
Földesi Mihály (FoldesiStudio.hu)

**Comment by borazslo** [comment]
Kedves @foldesistudio ! Bátran fogadjuk a segítséget. Most épp újra tudok kicsit dolgozni rajta. A Szent József Hackathonon dockerizáltuk az egészet és most a fejlesztői környezet pár kattintással elindul. És az remek hír.

Illetve a konkrét javaslatra is volt reakció: 3d17f3ccec2a800975fb58fc5f6ad4d549813087
