### ISSUE TITLE
API (readonly) megnyitása

### ISSUE THREAD

**Issue by hdadr** [borazslo/miserend.hu#159]
Hozzájárulhatna, hogy mások saját mobilos vagy webes felületet fejleszthessenek hozzá.

**Comment by borazslo** [comment]
Nyilvános API elérhető többféle funkcióval és örömmel látunk mindenféle mobilos vagy webes fejlesztést: https://github.com/borazslo/miserend.hu/wiki/API

**Comment by hdadr** [comment]
> Nyilvános API elérhető többféle funkcióval és örömmel látunk mindenféle mobilos vagy webes fejlesztést: https://github.com/borazslo/miserend.hu/wiki/API

Most jutottam oda, hogy tudjak vele foglalkozni. 
Két dolog:
- Egyik, hogy olyan API-ra gondoltam, ahol tudok szűrni rekordokat, és nem csak azt tudom kiszűrni, hogy milyen oszlopokat kérek. Amennyiben jól értem, hogy a listák és táblázatok fejezet alatt az megy. Máshol nem találtam lekérdezésre példát, hogy például a város alapján (vagy templomnév ...) a templomokat vissza adja, a templomokkal meg a hozzá csatolt miséket. Kvázi azt szeretném, hogy mint a miserend.hu kezelőfelületén lehet szűrni adatokat, ugyan azokkal a szűrőkkel szűrnék én is, csak más frontenden. 

- Másik, pedig miserend.hu/fajlok/sqlite/miserend_v4.sqlite3 linken, ha jól sejtem a v4 adatbázis található. Régebben még letöltöttem, akkor megtudtam nyitni localban sqlite3 kezelővel, de most hogy letöltöttem és próbálnám megnyitni, azt írja, hogy a fájl sérült vagy helytelen.

**Comment by hdadr** [comment]
Vajon küld értesítőt a github, ha lezárt issue-hoz kommentelek? 🤔

**Comment by borazslo** [comment]
Juj. Küld...

- A https://miserend.hu/fajlok/sqlite/miserend_v4.sqlite3 most már remélem jó fájl és újra működik a generálás és mindig friss.

- Eddig nem volt részletes API lekérésekre és szűrésre, mondván hogy "olcsóbb" az egész adatbázis lehúzni és arra építeni mindent. De ez nem biztos, hogy igaz. De azért lett most egy API végpont, ahol egy adott koordinátához legközelebbi templomokat és miséit adja vissza. WiKi-ben hogy hogyan (json-ban küldeni kell egy lat-lon kombinációz).

De igazából tudom támogatni, hogy épülhessen teljesen új frontend is akár. De azért ahhoz nem csak templom és mise adatok, hanem sok minden más is kéne.

De ha írsz egy-két konkrét APP végpontot és hogy hogyan iselkedjen, akkor talán mostanában tudok gyártani egy kettőt.

**Comment by hdadr** [comment]
> A https://miserend.hu/fajlok/sqlite/miserend_v4.sqlite3 most már remélem jó fájl és újra működik a generálás és mindig friss.
Köszi, ez most egyelőre elég lesz.

> De ha írsz egy-két konkrét APP végpontot és hogy hogyan iselkedjen, akkor talán mostanában tudok gyártani egy kettőt.
Még én sem tudom, hogy hogyan lenne jó strukturálni a lekérdezést, mert még a frontenden sem teljesen tiszta a UI/UX.

**Comment by hdadr** [comment]
> De ha írsz egy-két konkrét APP végpontot és hogy hogyan iselkedjen, akkor talán mostanában tudok gyártani egy kettőt.

Látom nagy munkában vagytok, így megértem, ha erre várni kell. 

Következő endpoint-okat tudnám használni: 
- **api/cities**: Ami egy JSON string  array-t **["Budapest", "Szeged",...]** ad vissza. Az adatbázisban található városok listája, valami ilyesmi: *SELECT DISTINCT varos FROM templomok WHERE varos IS NOT NULL*. IS NOT NULL nélkül belekerül valami null szerűség. Input autocomplete-hez tudnám felhasználni frontenden, hogy segítse a usert a város helyes beviteléhez. 
- **api/church-names**: return JSON string array  **["Szent Ferenc-templom", "Havas Boldogasszony-kápolna",...]** . Az adatbázisban található templom nevek. *SELECT DISTINCT nev FROM templomok*. Szintúgy autocomplete-hez.
- **api/churches**: return JSON object array **[{tid, ..., misek: [tid, mid, ...], kepek: [tid, kid,...]}, {...}, ... ]**. Object meg úgy nézne ki, hogy tartalmazza a templom minden adatát, hozzá véve az összes miséjét és képét, és város alapján lenne szűrve. Ha ezt megkapom, akkor már minden más alapján való szűrést eltudom végezni frontenden. Ezeket a templom adatokat cachelném frontenden egy ideig, hogy azért ne minden ilyen keresés terhelje a szervert.  Az sql valami ilyesminek néz ki, de programatikusan is elő lehetne állítani az objektumokat. 
```sql
SELECT templomok.*,  
  (SELECT json_group_array(json_object(
    'mid', mid, 
    'tid', tid, 
    'periodus', periodus, 
    'idoszak', idoszak, 
    'suly', suly, 
    'datumtol', datumtol, 
    'datumig', datumig, 
    'nap', nap, 
    'ido', ido, 
    'nyelv', nyelv, 
    'milyen', milyen, 
    'megjegyzes', megjegyzes)) 
  FROM misek WHERE misek.tid = templomok.tid) as misek,
  (SELECT json_group_array(json_object(
    'kid', kid,
    'tid', tid,
    'kep', kep)) 
  FROM kepek WHERE kepek.tid = templomok.tid) as kepek 
FROM templomok WHERE varos LIKE ?

**Comment by hdadr** [comment]
Közben találtam egy megoldást, hogy ideiglenesen tudjam deployolni az sqlite db-t. Szóval nekem ráér ez a bővítés, mert még lehet később máshogy alakul, hogy mire lenne szükség.

**Comment by borazslo** [comment]
De jó! Köszi a türelmet! Mert most ez a kódátépítés jó nagy falat és ehhez már én kicsi vagyok. Addig meg kicsit áll az én részem. de halad és nagyon izgi. :D

**Comment by hdadr** [comment]
A miserend.hu honnan szedi a templomokhoz kapcsolódó plusz adatokat, mint pl a bemutatkozás, kapcsolat, kapcsolódó információk?

**Comment by borazslo** [comment]
Jelenleg saját adatbázis. OSM-ről van a koordináta és az akadálymentességi adataok. Idővel szeretném, ha a miserenden és fotókon kívül minden OSM lenne. Még ha némi adatvesztéssel is jár (mert ott 255 karakter limit van minden tag-nél).

**Comment by hdadr** [comment]
Van rá lehetőség, hogy megkapjam az adatbázist? 
Jelenleg egy prototípust építek, így nem kerülne ki közönség elé, legalábbis mielőtt nem mutatom meg neked és kapok rá engedélyt.

**Comment by borazslo** [comment]
dobj egy emailt: ***@***.***

hda ***@***.***> ezt írta (időpont: 2024. jan. 16., K, 16:29):

**Comment by hdadr** [comment]
> dobj egy emailt. profilomon a címem eleklaszlosj gmail

Elvileg küldtem emailt. De lehet az lesz, hogy elég a miserend db-ben levő adatok (misék időpontja, plusz a hely koordináták), és egy linket raknék ki, ami elvezet a miserend.hu adott templomjára a további adatokért.
