### ISSUE TITLE
Nem töltenek be a templomok képei

### ISSUE THREAD

**Issue by baueri** [borazslo/miserend.hu#167]
403-as hibakóddal elszállnak a képbetöltések, pl.:

https://miserend.hu/templom/1037

![image](https://github.com/borazslo/miserend.hu/assets/11177064/a2d6e050-d4d8-4ec0-b2e6-2f1442f3d3dc)

**Comment by MMate2007** [comment]
Ugyanez a főoldalon is a bal felső sarokban.

**Comment by borazslo** [comment]
Upsz. Javítva. 
(chown izék voltak, mert háttérben backupoztam. bocsesz)

**Comment by baueri** [comment]
Helyreáll a rend! :) Köszi!
