### ISSUE TITLE
Docker [Note] Access denied for user 'user'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by MMate2007** [borazslo/miserend.hu#168]
Sem a miserendhu, sem a pma konténer nem tud csatlakozni a MySQL-hez. A root felhasználóval próbálkozva ugyanez.
root felhasználóval csak az alapértelmezett üres jelszóval lehet bejutni. Bejutás után látszódik, hogy valamiért a user felhasználó nem jön létre, ahogy a miserend adatbázis sem. A dump.sql fájl azonban a helyére kerül, de nem hajtódik végre.

**Comment by borazslo** [comment]
Légyszi segíts még kicsit debuggolni, mert nem sikerül eléggé reprodukálni a problémát.

- Windows 10 Pro (ez fontos!), Docker 4.17.1, 
- Ha nem teljesen nulláról indulsz, akkor a Docker-ben a "Volumes" részben ki kell törölni a megfelelő `db_data`-t, mert egy átlag `docker-compose build` ezt nem építi újjá!
- Lehet hogy a ./docker/entrypoint_miserend.sh -ban a sorvégeket CRLF-ről LF-re kell állítani. (De ez a miserend konténert érinti a többit nem.)
- `docker-compose build` (vagy `docker compose build`) majd `docker compose up` és nekem szépen elindult
- A PMA konténert böngészőben megnyitva simán be tudtam lépni: kiszolgáló: mysql, felhasználónév: user, jelszó: pw. 
 
Sima ügy nálam. Nálad?

**Comment by MMate2007** [comment]
- Windows 10 Home-ot használok Docker v4.22.1-el , eddig nem volt semmi baj a Dockerrel, futott szépen. Linuxon sajnos nem tudom kipróbálni, hogy hogyan fut, mert a linuxos gépemben ARM processzor van és úgy tűnik, vannak konténerek, amik nem támogatják az ARM procikat.
- docker-entrypoint.sh-ban átállítottam a sorvégeket LF-re.

Update: most működik. Lehet, hogy az volt a gond, hogy nem futtattam le a build parancsot az up előtt? Töröltem a `db_data` volume-ot, utána `docker compose build`, `docker compose up` és működik.
