### ISSUE TITLE
kód nagyobb átszervezése

### ISSUE THREAD

**Issue by connorhu** [borazslo/miserend.hu#175]
- [x] Az alábbi mappa struktúra jöjjön létre: assets, config, docker, public, src, templates, tests
- [x] Router ami azért felelős, hogy minden oldal egyértelműen kapcsolva legyen az osztályhoz vagy később a controllerhez
- [x] asset buildelés
- [x] build folyamat ami elkészíti az asseteket és feltelepít minden composer vendor filet
- [x] container, dependency injection
- [x] symfony/form alapok a formokhoz
- [x] symfony/validator alapok a formokhoz

**Comment by connorhu** [comment]
2: https://github.com/connorhu/miserend.hu/commit/97e1875a03859dde7246f9e4bf4fc00b9d772a83#diff-49f85e048f5c32adfcde7547d20e63c3b49c9ad174c36ef706e5fb4eb5b63753

Imígyen néz ki a router.

**Comment by connorhu** [comment]
> 4 Már főként (upsz) Bootstrap 5 van telepítve/használatban.

Akkor viszont kiszedem a 3-at és marad az öt. Megnézzük mit csinál így.

**Comment by connorhu** [comment]
Ahogy a művelt angol mondja so close yet so far.
![kép](https://github.com/borazslo/miserend.hu/assets/1845575/0183f416-68ef-4d57-a207-555caeef1493)

**Comment by borazslo** [comment]
A dupla bootstrap bár igen ocsmány dolog, de szerintem kisebb baj, mintha emiatt akadna el az átalakítás. Inkább átenném egy külön issue-be a bootstrap 3 kiiktatását. Azzal például még én is tudok játszani, hogy a .twig fájlokban javítgatom a helyzetet. De a nagy, rendszerszintű alakításokhoz nem értek eléggé és ne emiatt álljon a munka.

**Comment by connorhu** [comment]
Ha tudod nézegetni a branchet amit csináltam a PR-hoz akkor abból látszik, hogy mi a teendő. Vagy csinálsz egy külön branchet és abba beolvasztjuk a PR-t és az nem kerül ki az élesbe. Nem annyira vészes egyébként a BS migráció. Tegnap éjjel azért pár apróságra rátaláltam. A symfony port amit egy másik branchben kezdtem el csinálni az már egészen barátságosan nézett ki.

**Comment by connorhu** [comment]
Másodjára sikerült integrálni a symfony-t olymódon, hogy a ha a router szabályoknál meg van adva egy speciális érték, akkor azt továbbadja a symfonynak. Így felmenő rendszerben, funkciónként lehet átrakni a kódot. Erről nyitok majd egy új issue-t a teendőkkel.

**Comment by connorhu** [comment]
ezt pedig lezárjuk. az átszervezés megtörtént, van meg teendő, de az már más lapra tartozik.
