### ISSUE TITLE
email küldés nem megy

### ISSUE THREAD

**Issue by baueri** [borazslo/miserend.hu#186]
Elfelejtett jelszókéréskor.

![image](https://github.com/borazslo/miserend.hu/assets/11177064/885e4baf-7cb4-4fff-9f8f-548980df1a54)

**Comment by borazslo** [comment]
Új szerverre dobták át a PPKE-hez a cuccot pár napja. Kiderült, hogy a tűzfalon nem jut ki semmi. Elvileg beállították, de a curl azóta sem találja a hostot. És szemmel láthatóan az smtpConnect() sem megy. :( És Grrrr.

**Comment by connorhu** [comment]
Mi a host és mi a port?

**Comment by baueri** [comment]
+1 javaslat, hogy az explicit hibaüzenetek (stack trace stb) helyett majd lehetne egy sima 500-as "emberbarát" üzenetet küldeni a júzernek, háttérben pedig mehet az email a fejlesztőknek, vagy:

+2 sentry-t bekötni

**Comment by borazslo** [comment]
Kedves @connorhu és @baueri  ismerkedjetek össze. :D @baueri  is itt-ott belenyúlna majd a kódba ráadásul ő tud szépen kódolni velem ellentétbe, de most azt hiszem megvárja amíg egy olyan staging módban el tud indulni majd a pull request a mergelés után vagy mi.

**Comment by connorhu** [comment]
Néhány alap dolgot megcsinálok még, aztán látható lesz, hogy mivel hogyan kell bánni. Akkor akár egy másik branchba beolvasztható lesz a kód és nem egy PR-ba kell dolgoznom. Akkor már bele lehet nyúlni.
Egyébként bármi változtatást viszonylag könnyen beolvasztok rebase-zel, de lényegesen könnyebb dolgom van ha nem változik sokat a master és a production.

**Comment by baueri** [comment]
Türelemmel kivárom, addig is ismerkedek még ezzel a symfony-s struktúrával.

**Comment by connorhu** [comment]
Nem vészesen bonyolult. MVC, elég nagy szabadsággal és doctrine ORM-mel. Jól dokumentált, az új kódokban igyekszem a bevált fogásokat alkalmazni.

**Comment by borazslo** [comment]
@baueri : csináltunk nagy merge-t. Így az élesen a production van kinn, és a master ahol a nagy munka folyik. A "legacy" dolgok a régi zagyvák, és a többi ami már szép. Most sok kis pull request az irány, és így kezdődhet a párhuzamos itt-ott szépítés és munka is. Elvileg egy jó .env.local -al a `docker compose up` is szépen működik (nekem win alatt még recseg).

**Comment by baueri** [comment]
Szuper, már fel is frissítettem a forkot a masterből! :)

**Comment by connorhu** [comment]
Még vár pár PR, az után jobb lesz a master.

**Comment by borazslo** [comment]
Az új PPKE szerverről nem engednek ki a gmail smtp-je felé. De kapok @hcbc.hu email címet és annak az smtp szerveréhez átengednek (mert ugyan ott van) és akkor újra lesz levél. Hát gratulálok a tempóért... :(

**Comment by connorhu** [comment]
Hát ha hozzáférsz a DNS-hez és be tudod állítani az SFP-t, hogy miserend küldhessen egy adott IPről akkor tudok adni smtp szervert amin keresztül kimehetnek a levelek.

**Comment by borazslo** [comment]
- hcbc-ről mennek ki az emailek. A google elsőre elhajigálta mindet, mert a rendszer csalni próbált és más nevében küldött ki emailt, mint ami ő. De most már megy.
- Normális 500-as errorok továbbra sincsenek sajnos.
- De a /health oldal lefuttat jópár ellenőrzést, hogy látszódjék hogy mindenhez hozzáférünk és minden küldő kapcsolat működik-e.
