### ISSUE TITLE
codecov regisztráció

### ISSUE THREAD

**Issue by connorhu** [borazslo/miserend.hu#199]
https://app.codecov.io/gh/borazslo/miserend.hu

Regisztrálj légyszíves, hogy lássunk metrikát arról, hogy mennyire tesztelt a kódbázis és miben kell még javulni. Köszi!

**Comment by borazslo** [comment]
Regisztrálva,  és betettem a repository secretbe a tokent. Mehet a workflowba az izé:

- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v4.0.1
  env:
    token: ${{ secrets.CODECOV_TOKEN }}
    slug: borazslo/miserend.hu

**Comment by connorhu** [comment]
Kösziii!
