### ISSUE TITLE
Nem érhető el a miserend.hu

### ISSUE THREAD

**Issue by baueri** [borazslo/miserend.hu#217]
`ERR_ADDRESS_UNREACHABLE`

**Comment by borazslo** [comment]
grrrrr... semmihez nem nyúltam... :( Nézem

**Comment by baueri** [comment]
Megint valami portot nem engednek át?

**Comment by connorhu** [comment]
Biztonságos szerver ismérve. Nem érhető el sehonnan.

**Comment by connorhu** [comment]
A host-on lesz a probléma mert a hálózat működik. 193.225.109.4 betölt, a 193.225.109.12 nem.

**Comment by borazslo** [comment]
"Tudunk a problémáról. Szíves türelmedet kérjük.

Csütörtök délután 17.20 körül elromlott egy poe switch, ezért jelenleg egyetlen szerver és egyéb eszköz sem érhető el, ami ahhoz csatlakozott :-("

**Comment by connorhu** [comment]
Ahhoz csatlakozó dolgok száma: 1 db :D

**Comment by baueri** [comment]
Úgy látom helyreállt a rend :) Részemről zárható.
