### ISSUE TITLE
Templom mise megjegyzésben link beszúrásakor az URL helytelenül egyszerűsödik

### ISSUE THREAD

**Issue by MMate2007** [borazslo/miserend.hu#238]
A templom adatlapját szerkesztve a miserend megjegyzésbe *https://miserend.hu* kezdetű linket beszúrva az *../valami*-re egyszerűsödik helytelenül, így egy nem működő linket eredményez.
Példa: a link: *https://miserend.hu/templom/5005*, ezt bemásolva a szerkesztőbe lesz belőle: *../5005*. A szerkesztő előnézetében jól jelenik meg, de mentés után a templom oldalán már rossz link van a href-ben.

**Comment by borazslo** [comment]
Hát most már jó

**Comment by MMate2007** [comment]
Köszönöm!
Ezt lehetne merge-lni a main branch-re is?
Látom, hogy a production valamiben előrébb, valamiben hátrébb van...

**Comment by borazslo** [comment]
Tökéletlen a helyzet. :(
A main branch-on elkezdődött még december végén egy tök nagy és alapvető átalakítás. Egyféle teljes újralapozás. Amihez én egyszerűen nem értek és nekem túl komplex. Ezért a fejlesztések és javítások be lettek fagyasztva addig amíg a main branch átalakításai el nem készülnek.
Csakhogy az élet hullámai miatt @connorhu munkálatai lelassultak a main-ben. A production-ben viszont hétköznapi működést gátoló komoly gázok voltak. Ezért most neki estem a hetekben ahhoz amihez értegetek és a production branchen javítottam sokat. És ott komolyat léptem az adatbázis egyszerűsítésben is meg minden. Csakhát az a káoszos kódom és nem a szép. 
És így most hátraltatom a main branch előrehaladását amit sajnálok. De legalább halad előre az éles honlap működése ami meg már nagyon kellett. 

:(

**Comment by MMate2007** [comment]
Értem. 
Symphony-hoz nem értek sokat, így én csak ha nagyon egyszerű hibákat találok, esetleg azokat tudom javítani.

**Comment by MMate2007** [comment]
Akkor ez a hiba megoldódott.
Köszönöm még egyszer.
