### ISSUE TITLE
Mysql injection lehetősége mindenfelé

### ISSUE THREAD

**Issue by borazslo** [borazslo/miserend.hu#29]
és a már elavult mysql_query használata. Szükséges a PDO-ra áttérés.

**Comment by borazslo** [comment]
Elkezdődött a Laravel adatbázis kezelő osztályaival: 39d7e29cb568bb9db411512209e971d2f39a2fb0

**Comment by connorhu** [comment]
mysql_query-t tartalmazó fájlok:

classes/html/eventscatalogue.php
functions.php
classes/remark.php
classes/html/church/editschedule.php
classes/user.php
classes/html/ajax/eventslist.php
classes/api/updated.php
classes/html/ajax/autocompleteevents.php
classes/html/ajax/autocompletename.php
classes/html/ajax/chatsave.php
classes/html/church/delete.php
classes/html/diocesecatalogue.php
classes/mail.php
classes/api/table.php
classes/html/church/church.php
classes/html/josm.php
classes/html/searchresultsmasses.php

**Comment by borazslo** [comment]
Ami még maradt:

- classes/html/eventscatalogue.php
- functions.php
- classes/remark.php
- classes/html/church/editschedule.php
- classes/html/ajax/autocompletename.php
- classes/html/ajax/chatsave.php
- classes/api/table.php
- classes/html/josm.php

**Comment by borazslo** [comment]
@connorhu : Nem tudom, hogyan jobb felvenni a kapcsolatot, hát így próbálkozom. :D Örülök a fork-nak és minden ötletet, segítséget örömmel fogadok. És szívesen segítek felállítani egy dev környezetet pl. egész nagy minta adatbázis átküldésével (a mysql_sample most nem pontos). Szóval bármit. Elérhetőségem: https://miserend.hu/impresszum

**Comment by connorhu** [comment]
@borazslo nézegetem a kódot :) Volt egy félreértés. Azt hittem, hogy laravel nem csak a db hanem a website is. Aztán láttam, hogy nem. Alapvetően a frameworkök használata nem egy rossz ötlet, mondjuk én symfonyt használok mindenhol.
Az első célom az lenne, hogy a dev környezet összeállításához ne kelljen segítség. Valami jól használható DBAL/ORM, verziózott séma és fixture a kezdeti adatok betöltésére, telepítéshez.

**Comment by borazslo** [comment]
@connorhu : Mindent támogatok! Én botcsinálta programozó vagyok. A [szentiras.hu](https://github.com/borazslo/szentiras.hu)t állította át egy profi laravelre és azt tanulmányozgatva / kontárkodva kezdtem lépésről lépésre legalább részben áttérni itt, a miserend.hu -n. De arra esélyem sem volt, hogy egyben áttegyem az egészet. Se hozzáértésem, se időm-erőm. Ennek a nyoma, hogy van még mysql_query is.  És a szentiras.hu-s teljesen automata deployment is csak nyomokban van itt, mert ennyire értek hozzá. Szóval bármilyen alakítást örömmel veszek és megpróbálom tudásomban a lépést tartani a fejlődéssel.

**Comment by borazslo** [comment]
Meg baromi régi a laravel is, de még az alap debian is, meg minden.

**Comment by borazslo** [comment]
Ami maradt: functions.php

De abban sok minden van, amit rendesebben kéne egészen átformálni.

**Comment by connorhu** [comment]
(Tanulmányozom az oldal kódját, hogy szerver oldal teljes újraírása mi munka lenne.)

**Comment by connorhu** [comment]
Lezárható

**Comment by borazslo** [comment]
A soooook sok új átalakítás miatt, immáron boldog véget ért ez az issue
