### ISSUE TITLE
Megszűnt/Tiltott templomok

### ISSUE THREAD

**Issue by borazslo** [borazslo/miserend.hu#46]
Ha be van állítva, hogy "Nem jelenhet meg", akkor nem kéne megjelennie. Például: http://miserend.hu/?templom=2589
- a kereső nem talál rá, nagyon helyesen
- a megjelenítő megjeleníti (csak nagyon adminnak kéne)
- (keresésnél a város listában megjelenik az a település is, amin csak letiltott templomok vannak)

**Comment by annatombi** [comment]
Továbbra is érkezik észrevétel a régebben letiltott templomhoz.
Törölni nem helyes, hiszen sok még szerepel a sematizmusokban, pedig már nem léteznek és újra rögzítésre kerülhetnek.

**Comment by borazslo** [comment]
Remélem megoldva.
