### ISSUE TITLE
Templom szerkesztő: mentés után fehér halál

### ISSUE THREAD

**Issue by borazslo** [borazslo/miserend.hu#48]
Állítólag: A templom szerkesztő gyakran, új templom felvitele estén pedig mindig, a mentésre kattintás után bár elmenti az adatokat, de csak egy üres fehér oldalt ad vissza. Frissítésre (és ezzel az adatok újraküldésére ?) rendesen reagál és gond nélkül tovább jut. (Opera böngészővel).

**Comment by annatombi** [comment]
Templom módosításánál is, de csak akkor történik, ha a GPS-t beírom vagy javítom.

**Comment by borazslo** [comment]
Megoldva? .
